[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor = "#2c2420"
backgroundColor = "#ede8e2"
secondaryBackgroundColor = "#e2dbd4"
textColor = "#2c2420"
font = "sans serif"
